#!/usr/bin/env bash
# Configure an Nginx server to listen on port 80

# create symbolic link between nginx and enabled sites dir
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx
service nginx start
# terminate the first nginx process ID
kill "$(pgrep 'nginx' | head -1)"
